apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: boshdeployments.fissile.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: fissile.cloudfoundry.org
  names:
    kind: BOSHDeployment
    listKind: BOSHDeploymentList
    plural: boshdeployments
    singular: boshdeployment
  scope: Namespaced
  version: v1alpha1
